version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: banana-bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banana_bank_dev
    ports:
      - "5432:5432"